[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "puffercmd"
version = "13.0.0"
description = "no description provided."
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "anonymous", email = "liuwei@live.ca"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "requests>=2.0.0"
]

[project.urls]
Homepage = "https://github.com/skrmp94rx8-beep/puffercmd"
Repository = "https://github.com/skrmp94rx8-beep/puffercmd"
